


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./componant/Navebar/page";
import Footer from "./componant/footer/page";
import ReduxProvider from "./componant/reduxprovider";
import { ClerkProvider, SignedOut, SignInButton, SignedIn, UserButton } from "@clerk/nextjs";
// import Shoes from "./componant/Shoes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     
   
      

<ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
          <ReduxProvider> 
        <Navbar />
        {children}
      
        
       </ReduxProvider>
          {/* <Footer /> */}
     </body>
    </html > 
         
    </ClerkProvider>
    
  );
}
